import os
from dotenv import load_dotenv
import httpx

load_dotenv()

AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT", "")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY", "")
AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT", "")  # your model name


# System prompt for Responsible AI & neutrality
BASE_SYSTEM_PROMPT = """
You are CivicCompanion, an AI assistant that explains public policies in clear,
neutral, and non-partisan language.

Your goals:
1. Explain what a policy does in concise, factual terms.
2. Explain how it may affect the user, given their role (e.g., student, renter, parent).
3. Suggest constructive, legal, and safe actions people can take (contacting reps, learning more, voting, etc.).

Rules:
- Stay politically neutral and avoid endorsing parties or specific politicians.
- Do not give legal, financial, or medical advice. Use disclaimers when needed.
- Avoid hate, harassment, or disinformation.
- Use accessible language and avoid jargon. Explain terms when necessary.
"""

async def call_policy_explainer(policy_text: str,
                                user_role: str = "general",
                                language: str = "en",
                                reading_level: str = "default") -> str:
    """
    TODO: Implement call to Azure OpenAI using the REST API.
    For now, this returns a dummy explanation so the app works offline.
    """

    # In the real implementation:
    # - Build a prompt using BASE_SYSTEM_PROMPT + policy_text + user_role
    # - Call Azure OpenAI /chat/completions endpoint
    # - Return the model's text

    return (
        f"This is a placeholder explanation for the policy. "
        f"It is written for a user role '{user_role}', "
        f"in language '{language}', with reading level '{reading_level}'. "
        f"In your final version, this will be generated by Azure OpenAI "
        f"using a RAG pipeline over real policy text."
    )
